export const foodList = [
  {
    id: "0_shava",
    image: "/img/menuimages/shavamini.jpg",
    fullimage: "/img/menuimages/shava.jpg",
    name: "шаурма",
    description:
      "(лаваш, мясо куриное, капуста, морковь по-корейски, огурец, помидор, соус",
    pricelist: [
      { pricename: "средний вес: 280г (мясо 80г)", price: "25 руб" },
      { pricename: "средний вес: 360г (мясо 130г)", price: "32 руб" },
      { pricename: "средний вес: 450г (мясо 200г)", price: "40 руб" },
      { pricename: "средний вес: 560г (мясо 280г)", price: "56 руб" },
      { pricename: "средний вес: 1000г (мясо 400г)", price: "75 руб" },
    ],
  },
  {
    id: "1_kebab",
    image: "/img/menuimages/kebab.png",
    fullimage: "/img/menuimages/kebabmini.png",
    name: "люля-кебаб",
    description: "лаваш, люля-кебаб, капуста, морковь по-корейски, помидор, огурец, белый соус",
    pricelist: [
      { pricename: "люля-кебаб 1шт, средний вес: 260г", price: "30 руб" },
      { pricename: "люля-кебаб 2шт, средний вес: 350г", price: "38 руб" },
      { pricename: "люля-кебаб 3шт, средний вес: 450г", price: "48 руб" },
    ],
  },
  {
    id: "2_suluguni",
    image: "/img/menuimages/suluguni-v-lavashe.jpg",
    fullimage: "/img/menuimages/suluguni-v-lavashemini.jpg",
    name: "сулугуни в лаваше",
    description: "лаваш, сыр сулугуни, листы салата, пекинская капуста, помидор, белый соус",
    pricelist: [
      { pricename: "средний вес: 260г", price: "38 руб" },
      { pricename: "+мясо куриное, средний вес: 350г", price: "45 руб" },
    ],
  },
  {
    id: "3_hot-dog",
    image: "/img/menuimages/hotdog.jpg",
    fullimage: "/img/menuimages/hotdogmini.jpg",
    name: "хот-дог",
    description: "булочка, сосиска (мясо), соус",
    pricelist: [
      { pricename: "студенческий (сосиска куриная, морковь по-корейски)", price: "13 руб" },
      { pricename: "классический (сосиска свинина/курица, морковь по-корейски)", price: "17 руб" },
      { pricename: "французский (копчёная мясная сосиска)", price: "18 руб" },
      { pricename: "с мясом (рубленное куриное мясо, помидор)", price: "18 руб" },
      { pricename: "с мититеей (мититея, помидор)", price: "18 руб" },
    ],
  },
  {
    id: "4_hambutger",
    image: "/img/menuimages/gamburger.jpg",
    fullimage: "/img/menuimages/gamburgermini.jpg",
    name: "гамбургер",
    description:
      "булочка, салатный лист, котлета (свинина/телятина), помидор, огурец, 3 вида соуса",
    pricelist: [{ pricename: "", price: "26 руб" }],
  },
  {
    id: "5_chickenbutger",
    image: "/img/menuimages/chickenburger.jpg",
    fullimage: "/img/menuimages/chickenburgermini.jpg",
    name: "чикенбургер",
    description:
      "булочка, салатный лист, рубленное куриное мясо, помидор, огурец, 3 вида соуса",
    pricelist: [{ pricename: "", price: "25 руб" }],
  },
  {
    id: "6_cheesebutger",
    image: "/img/menuimages/cheeseburger.jpg",
    fullimage: "/img/menuimages/cheeseburgermini.jpg",
    name: "чизбургер",
    description:
      "булочка, салатный лист, котлета (свинина/телятина), сыр сулугуни, помидор, огурец, 3 вида соуса",
    pricelist: [{ pricename: "", price: "30 руб" }],
  },
  {
    id: "7_bigburger",
    image: "/img/menuimages/bigburger.jpg",
    fullimage: "/img/menuimages/bigburgermini.jpg",
    name: "бигбургер",
    description: "(булочка, салатный лист, 2 котлеты (свинина/телятина), помидор, огурец, 3 вида соуса",
    pricelist: [{ pricename: "", price: "45 руб" }],
  },
  {
    id: "8_frenchfry",
    image: "/img/menuimages/frenchfry.jpg",
    fullimage: "/img/menuimages/frenchfrymini.jpg",
    name: "картофель фри",
    description: "картофель фри, специи",
    pricelist: [
      { pricename: "средний вес: 100г", price: "17 руб" },
      { pricename: "средний вес: 170г", price: "22 руб" },
    ],
  },
  {
    id: "9_nuggets",
    image: "/img/menuimages/chickenwings.jpg",
    fullimage: "/img/menuimages/chickenwingsmini.jpg",
    name: "наггетсы",
    description: "куринные наггетсы",
    pricelist: [
      { pricename: "средний вес: 100г", price: "20 руб" },
      { pricename: "средний вес: 160г", price: "28 руб" },
    ],
  },
];

export const addsList = [
  {
    id: "0_cheese",
    image: "/img/menuimages/cheese.jpg",
    fullimage: "/img/menuimages/cheesemini.jpg",
    name: "сыр",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "1_meet",
    image: "/img/menuimages/meet.jpg",
    fullimage: "/img/menuimages/meetmini.jpg",
    name: "мясо",
    description: "мясо куриное",
    pricelist: [{ pricename: "", price: "7 руб" }],
  },
  {
    id: "2_more-french-fry",
    image: "/img/menuimages/frenchfryadd.jpg",
    fullimage: "/img/menuimages/frenchfryaddmini.jpg",
    name: "картофель фри",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "3_sause",
    image: "/img/menuimages/sous.jpg",
    fullimage: "/img/menuimages/sousmini.jpg",
    name: "соус",
    description: "",
    pricelist: [{ pricename: "", price: "3 руб" }],
  },
  {
    id: "4_mustard",
    image: "/img/menuimages/mustard.jpg",
    fullimage: "/img/menuimages/mustardmini.jpg",
    name: "горчица",
    description: "",
    pricelist: [{ pricename: "", price: "1 руб" }],
  },
  {
    id: "5_onion",
    image: "/img/menuimages/onion.jpg",
    fullimage: "/img/menuimages/onionmini.jpg",
    name: "маринованный лук",
    description: "",
    pricelist: [{ pricename: "", price: "1 руб" }],
  },
  {
    id: "6_milk",
    image: "/img/menuimages/milk.jpg",
    fullimage: "/img/menuimages/milkmini.jpg",
    name: "молоко",
    description: "",
    pricelist: [{ pricename: "", price: "2 руб" }],
  },
];

export const drinksList = [
  {
    id: "0_tea",
    image: "/img/menuimages/tea.jpg",
    fullimage: "/img/menuimages/teamini.jpg",
    name: "чай в ассортементе",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "1_coffee",
    image: "/img/menuimages/coffee.jpg",
    fullimage: "/img/menuimages/coffeemini.jpg",
    name: "кофе растворимый",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "2_coffeeinone",
    image: "/img/menuimages/coffeethreeinone.jpg",
    fullimage: "/img/menuimages/coffeethreeinonemini.jpg",
    name: "кофе 3-в-1",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "3_cocktail",
    image: "/img/menuimages/cocktail.jpg",
    fullimage: "/img/menuimages/cocktailmini.jpg",
    name: "молочный коктейль",
    description: "молоко, мороженое 3 шарика, сахарная пудра",
    pricelist: [
      { pricename: "классический", price: "18 руб" },
      { pricename: "шоколадный (+какао)", price: "18 руб" },
      { pricename: "банановый (+банан)", price: "21 руб" },
    ],
  },
  {
    id: "4_mojito",
    image: "/img/menuimages/mojito.jpg",
    fullimage: "/img/menuimages/mojitomini.jpg",
    name: "мохито",
    description: "мята, лайм, спрайт, тростниковый сахар, лед",
    pricelist: [{ pricename: "", price: "16 руб" }],
  },
];

export const comboList = [
  {
    id: "0_combo1",
    image: "/img/menuimages/combo1.jpg",
    fullimage: "/img/menuimages/combo1mini.jpg",
    name: "Гамбургер за 26 + фри за 17",
    description: "",
    pricelist: [{ pricename: "", price: "39 руб" }],
  },
  {
    id: "1_combo2",
    image: "/img/menuimages/combo2.jpg",
    fullimage: "/img/menuimages/combo2mini.jpg",
    name: "Фри за 22 + наггетсы за 20",
    description: "",
    pricelist: [{ pricename: "", price: "39 руб" }],
  },
  {
    id: "2_combo3",
    image: "/img/menuimages/combo3.jpg",
    fullimage: "/img/menuimages/combo3mini.jpg",
    name: "Фри за 22 + наггетсы за 28",
    description: "",
    pricelist: [{ pricename: "", price: "45 руб" }],
  },
  {
    id: "3_combo4",
    image: "/img/menuimages/combo4.jpg",
    fullimage: "/img/menuimages/combo4mini.jpg",
    name: "Гамбургер за 26 + наггетсы за 20",
    description: "",
    pricelist: [{ pricename: "", price: "41 руб" }],
  },
  {
    id: "4_combo5",
    image: "/img/menuimages/combo5.jpg",
    fullimage: "/img/menuimages/combo5mini.jpg",
    name: "Шаурма за 32 + фри за 17",
    description: "",
    pricelist: [{ pricename: "", price: "45 руб" }],
  },
];
