export const foodList = [
  {
    id: "0_shava",
    image: "/img/menuimages/shavamini.jpg",
    fullimage: "/img/menuimages/shava.jpg",
    name: "шаурма",
    description:
      "Лаваш, мясо, капуста, морковь, маринованный огурец, соль, перец",
    pricelist: [
      { pricename: "маленькая", price: "25 руб" },
      { pricename: "средняя", price: "32 руб" },
      { pricename: "большая", price: "40 руб" },
      { pricename: "очень большая", price: "56 руб" },
      { pricename: "огромная", price: "75 руб" },
    ],
  },
  {
    id: "1_kebab",
    image: "/img/menuimages/kebab.png",
    fullimage: "/img/menuimages/kebabmini.png",
    name: "кебаб",
    description: "мясо",
    pricelist: [
      { pricename: "маленький", price: "30 руб" },
      { pricename: "средний", price: "38 руб" },
      { pricename: "большой", price: "48 руб" },
    ],
  },
  {
    id: "2_suluguni",
    image: "/img/menuimages/suluguni-v-lavashe.jpg",
    fullimage: "/img/menuimages/suluguni-v-lavashemini.jpg",
    name: "сулугуни в лаваше",
    description: "лаваш, сыр сулугуни, помидор, зелень, масло",
    pricelist: [
      { pricename: "большой", price: "38 руб" },
      { pricename: "маленький", price: "45 руб" },
    ],
  },
  {
    id: "3_hambutger",
    image: "/img/menuimages/gamburger.jpg",
    fullimage: "/img/menuimages/gamburgermini.jpg",
    name: "гамбургер",
    description:
      "булочка, говяжья котлета, помидор, маринованный огурец, лист зеленого салата, кетчуп",
    pricelist: [{ pricename: "", price: "26 руб" }],
  },
  {
    id: "4_chickenbutger",
    image: "/img/menuimages/chickenburger.jpg",
    fullimage: "/img/menuimages/chickenburgermini.jpg",
    name: "чикенбургер",
    description:
      "булочка, куриная котлета, майонез, горчица, помидор, лист зеленого салата",
    pricelist: [{ pricename: "", price: "25 руб" }],
  },
  {
    id: "5_cheesebutger",
    image: "/img/menuimages/cheeseburger.jpg",
    fullimage: "/img/menuimages/cheeseburgermini.jpg",
    name: "чизбургер",
    description:
      "булочка, говяжья котлета, сыр, зеленый салат, помидор, маринованный огурец, майонез, кетчуп, горчица",
    pricelist: [{ pricename: "", price: "30 руб" }],
  },
  {
    id: "6_bigburger",
    image: "/img/menuimages/bigburger.jpg",
    fullimage: "/img/menuimages/bigburgermini.jpg",
    name: "бигбургер",
    description: "большой гамбургер",
    pricelist: [{ pricename: "", price: "45 руб" }],
  },
  {
    id: "7_hot-dog",
    image: "/img/menuimages/hotdog.jpg",
    fullimage: "/img/menuimages/hotdogmini.jpg",
    name: "хот-дог",
    description: "булочка (лаваш), сосиска (мясо), кетчуп, горчица",
    pricelist: [
      { pricename: "студенческий", price: "13 руб" },
      { pricename: "классический", price: "17 руб" },
      { pricename: "французский", price: "18 руб" },
      { pricename: "с мясом", price: "18 руб" },
      { pricename: "с мититеей", price: "18 руб" },
    ],
  },
  {
    id: "8_frenchfry",
    image: "/img/menuimages/frenchfry.jpg",
    fullimage: "/img/menuimages/frenchfrymini.jpg",
    name: "картофель фри",
    description: "",
    pricelist: [
      { pricename: "большой", price: "17 руб" },
      { pricename: "маленький", price: "22 руб" },
    ],
  },
  {
    id: "9_nuggets",
    image: "/img/menuimages/chickenwings.jpg",
    fullimage: "/img/menuimages/chickenwingsmini.jpg",
    name: "наггетсы",
    description: "",
    pricelist: [
      { pricename: "большой", price: "20 руб" },
      { pricename: "маленький", price: "28 руб" },
    ],
  },
];

export const addsList = [
  {
    id: "0_cheese",
    image: "/img/menuimages/cheese.jpg",
    fullimage: "/img/menuimages/cheesemini.jpg",
    name: "сыр",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "1_meet",
    image: "/img/menuimages/meet.jpg",
    fullimage: "/img/menuimages/meetmini.jpg",
    name: "мясо",
    description: "",
    pricelist: [{ pricename: "", price: "6 руб" }],
  },
  {
    id: "2_more-french-fry",
    image: "/img/menuimages/frenchfryadd.jpg",
    fullimage: "/img/menuimages/frenchfryaddmini.jpg",
    name: "картошка фри",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "3_sause",
    image: "/img/menuimages/sous.jpg",
    fullimage: "/img/menuimages/sousmini.jpg",
    name: "соус",
    description: "",
    pricelist: [{ pricename: "", price: "3 руб" }],
  },
  {
    id: "4_mustard",
    image: "/img/menuimages/mustard.jpg",
    fullimage: "/img/menuimages/mustardmini.jpg",
    name: "горчица",
    description: "",
    pricelist: [{ pricename: "", price: "1 руб" }],
  },
  {
    id: "5_onion",
    image: "/img/menuimages/onion.jpg",
    fullimage: "/img/menuimages/onionmini.jpg",
    name: "маринованный лук",
    description: "",
    pricelist: [{ pricename: "", price: "1 руб" }],
  },
  {
    id: "6_milk",
    image: "/img/menuimages/milk.jpg",
    fullimage: "/img/menuimages/milkmini.jpg",
    name: "молоко",
    description: "",
    pricelist: [{ pricename: "", price: "2 руб" }],
  },
];

export const drinksList = [
  {
    id: "0_tea",
    image: "/img/menuimages/tea.jpg",
    fullimage: "/img/menuimages/teamini.jpg",
    name: "чай в ассортементе",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "1_coffee",
    image: "/img/menuimages/coffee.jpg",
    fullimage: "/img/menuimages/coffeemini.jpg",
    name: "кофе растворимый",
    description: "",
    pricelist: [{ pricename: "", price: "5 руб" }],
  },
  {
    id: "2_cocktail",
    image: "/img/menuimages/cocktail.jpg",
    fullimage: "/img/menuimages/cocktailmini.jpg",
    name: "молочный коктейль",
    description: "",
    pricelist: [
      { pricename: "классический", price: "" },
      { pricename: "банановый", price: "" },
      { pricename: "кофейный", price: "" },
    ],
  },
  {
    id: "3_mojito",
    image: "/img/menuimages/mojito.jpg",
    fullimage: "/img/menuimages/mojitomini.jpg",
    name: "мохито",
    description: "",
    pricelist: [{ pricename: "", price: "" }],
  },
];

export const comboList = [
  {
    id: "0_combo1",
    image: "/img/menuimages/combo1.jpg",
    fullimage: "/img/menuimages/combo1mini.jpg",
    name: "Гамбургер за 26 + фри за 17",
    description: "",
    pricelist: [{ pricename: "", price: "39 руб" }],
  },
  {
    id: "1_combo2",
    image: "/img/menuimages/combo2.jpg",
    fullimage: "/img/menuimages/combo2mini.jpg",
    name: "Фри за 22 + наггетсы за 20",
    description: "",
    pricelist: [{ pricename: "", price: "39 руб" }],
  },
  {
    id: "2_combo3",
    image: "/img/menuimages/combo3.jpg",
    fullimage: "/img/menuimages/combo3mini.jpg",
    name: "Фри за 22 + наггетсы за 28",
    description: "",
    pricelist: [{ pricename: "", price: "45 руб" }],
  },
  {
    id: "3_combo4",
    image: "/img/menuimages/combo4.jpg",
    fullimage: "/img/menuimages/combo4mini.jpg",
    name: "Гамбургер за 26 + наггетсы за 20",
    description: "",
    pricelist: [{ pricename: "", price: "41 руб" }],
  },
  {
    id: "4_combo5",
    image: "/img/menuimages/combo5.jpg",
    fullimage: "/img/menuimages/combo5mini.jpg",
    name: "Шаурма за 32 + фри за 17",
    description: "",
    pricelist: [{ pricename: "", price: "45 руб" }],
  },
];
